import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.qlrppdrlyrxwluhbvkbb.supabase.co
const supabaseAnonKey = process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscnBwZHJseXJ4d2x1aGJ2a2JiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MzA4NzI4NiwiZXhwIjoyMDk4NjYzMjg2fQ.RFzvl5OREedm2AKqZLMdSgiJfIfFq3hsR2XJR-DgdSE
export const supabase = createClient(supabaseUrl, supabaseAnonKey)
